repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    # - id: terraform_checkov
    # - id: terraform_trivy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
    - id: detect-private-key
